version: '3.8'

services:
    app:
        build:
            context: ./docker
        container_name: laravel-app
        volumes:
            - .:/var/www
        depends_on:
            - mysql_db
        networks:
            - laravel

    mysql_db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - laravel

volumes:
    mysql_data:
        driver: local

networks:
    laravel:
        driver: bridge
